### ISSUE TITLE
Need help using the concave hull part of this repository.

### ISSUE THREAD

**Issue by justinjk007** [aviatorBeijing/concave_hull#5]
So I am writing a program in C++ and need to get the concave hull set of points as one of the operations.  From what I understand I need to include `hull.c` and `hull.h` into my respective files to gain access to what ever methods I need . But the problem is I don't know any `C` and don't really know what's going on. What method should I call **?** How to pass the `points` I have **?** What is returned **?** . I have no idea or clue about these things. Can someone guide me doing this . Thank very much for your time. Hopefully @aviatorBeijing is around.

My `point` struct is simple it has `point.x` -> storing the x-coordinate and `point.y` storing y-coordinate.

From what I found there is a `double find_alpha(simplex*)` So I guess i need to convert my `points` into this  `simplex` format. Any Idea how **?** . Or am i even on the right track here?

**Comment by aviatorBeijing** [comment]
Justin, Thanks for interested in the code. I'll check it out to see if I
can answer your concerns, next week maybe. I am buried by work at the
moment... :(   -Jun

**Comment by justinjk007** [comment]
Awesome. That's fine. I can wait till next week.

Err, or is possible over the weekend ?

**Comment by justinjk007** [comment]
Hello there! Can you find time this week

**Comment by justinjk007** [comment]
Hello, can you find time this week, sorry for the disturbance.

**Comment by justinjk007** [comment]
Hello @aviatorBeijing can you find some time this week possibly.

**Comment by aviatorBeijing** [comment]
Hi @justinjk007 

Please refer to: http://www.netlib.org/voronoi/hull.html   This was the original idea/source code came from.
